<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Icon extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('fontawesome')->insert([
            ['icon' => 'fa-500px','name' => 'fa 500px'],
            ['icon' => 'fa-address-book','name' => 'fa address book'],
            ['icon' => 'fa-address-book-o','name' => 'fa address book o'],
            ['icon' => 'fa-address-card','name' => 'fa address card'],
            ['icon' => 'fa-address-card-o','name' => 'fa address card o'],
            ['icon' => 'fa-adjust','name' => 'fa adjust'],
            ['icon' => 'fa-adn','name' => 'fa adn'],
            ['icon' => 'fa-align-center','name' => 'fa align center'],
            ['icon' => 'fa-align-justify','name' => 'fa align justify'],
            ['icon' => 'fa-align-left','name' => 'fa align left'],
            ['icon' => 'fa-align-right','name' => 'fa align right'],
            ['icon' => 'fa-amazon','name' => 'fa amazon'],
            ['icon' => 'fa-ambulance','name' => 'fa ambulance'],
            ['icon' => 'fa-american-sign-language-interpreting','name' => 'fa american sign language interpreting'],
            ['icon' => 'fa-anchor','name' => 'fa anchor'],
            ['icon' => 'fa-android','name' => 'fa android'],
            ['icon' => 'fa-angellist','name' => 'fa angellist'],
            ['icon' => 'fa-angle-double-down','name' => 'fa angle double down'],
            ['icon' => 'fa-angle-double-left','name' => 'fa angle double left'],
            ['icon' => 'fa-angle-double-right','name' => 'fa angle double right'],
            ['icon' => 'fa-angle-double-up','name' => 'fa angle double up'],
            ['icon' => 'fa-angle-down','name' => 'fa angle down'],
            ['icon' => 'fa-angle-left','name' => 'fa angle left'],
            ['icon' => 'fa-angle-right','name' => 'fa angle right'],
            ['icon' => 'fa-angle-up','name' => 'fa angle up'],
            ['icon' => 'fa-apple','name' => 'fa apple'],
            ['icon' => 'fa-archive','name' => 'fa archive'],
            ['icon' => 'fa-area-chart','name' => 'fa area chart'],
            ['icon' => 'fa-arrow-circle-down','name' => 'fa arrow circle down'],
            ['icon' => 'fa-arrow-circle-left','name' => 'fa arrow circle left'],
            ['icon' => 'fa-arrow-circle-o-down','name' => 'fa arrow circle o down'],
            ['icon' => 'fa-arrow-circle-o-left','name' => 'fa arrow circle o left'],
            ['icon' => 'fa-arrow-circle-o-right','name' => 'fa arrow circle o right'],
            ['icon' => 'fa-arrow-circle-o-up','name' => 'fa arrow circle o up'],
            ['icon' => 'fa-arrow-circle-right','name' => 'fa arrow circle right'],
            ['icon' => 'fa-arrow-circle-up','name' => 'fa arrow circle up'],
            ['icon' => 'fa-arrow-down','name' => 'fa arrow down'],
            ['icon' => 'fa-arrow-left','name' => 'fa arrow left'],
            ['icon' => 'fa-arrow-right','name' => 'fa arrow right'],
            ['icon' => 'fa-arrow-up','name' => 'fa arrow up'],
            ['icon' => 'fa-arrows','name' => 'fa arrows'],
            ['icon' => 'fa-arrows-alt','name' => 'fa arrows alt'],
            ['icon' => 'fa-arrows-h','name' => 'fa arrows h'],
            ['icon' => 'fa-arrows-v','name' => 'fa arrows v'],
            ['icon' => 'fa-asl-interpreting','name' => 'fa asl interpreting'],
            ['icon' => 'fa-assistive-listening-systems','name' => 'fa assistive listening systems'],
            ['icon' => 'fa-asterisk','name' => 'fa asterisk'],
            ['icon' => 'fa-at','name' => 'fa at'],
            ['icon' => 'fa-audio-description','name' => 'fa audio description'],
            ['icon' => 'fa-automobile','name' => 'fa automobile'],
            ['icon' => 'fa-backward','name' => 'fa backward'],
            ['icon' => 'fa-balance-scale','name' => 'fa balance scale'],
            ['icon' => 'fa-ban','name' => 'fa ban'],
            ['icon' => 'fa-bandcamp','name' => 'fa bandcamp'],
            ['icon' => 'fa-bank','name' => 'fa bank'],
            ['icon' => 'fa-bar-chart','name' => 'fa bar chart'],
            ['icon' => 'fa-bar-chart-o','name' => 'fa bar chart o'],
            ['icon' => 'fa-barcode','name' => 'fa barcode'],
            ['icon' => 'fa-bars','name' => 'fa bars'],
            ['icon' => 'fa-bath','name' => 'fa bath'],
            ['icon' => 'fa-bathtub','name' => 'fa bathtub'],
            ['icon' => 'fa-battery','name' => 'fa battery'],
            ['icon' => 'fa-battery-0','name' => 'fa battery 0'],
            ['icon' => 'fa-battery-1','name' => 'fa battery 1'],
            ['icon' => 'fa-battery-2','name' => 'fa battery 2'],
            ['icon' => 'fa-battery-3','name' => 'fa battery 3'],
            ['icon' => 'fa-battery-4','name' => 'fa battery 4'],
            ['icon' => 'fa-battery-empty','name' => 'fa battery empty'],
            ['icon' => 'fa-battery-full','name' => 'fa battery full'],
            ['icon' => 'fa-battery-half','name' => 'fa battery half'],
            ['icon' => 'fa-battery-quarter','name' => 'fa battery quarter'],
            ['icon' => 'fa-battery-three-quarters','name' => 'fa battery three quarters'],
            ['icon' => 'fa-bed','name' => 'fa bed'],
            ['icon' => 'fa-beer','name' => 'fa beer'],
            ['icon' => 'fa-behance','name' => 'fa behance'],
            ['icon' => 'fa-behance-square','name' => 'fa behance square'],
            ['icon' => 'fa-bell','name' => 'fa bell'],
            ['icon' => 'fa-bell-o','name' => 'fa bell o'],
            ['icon' => 'fa-bell-slash','name' => 'fa bell slash'],
            ['icon' => 'fa-bell-slash-o','name' => 'fa bell slash o'],
            ['icon' => 'fa-bicycle','name' => 'fa bicycle'],
            ['icon' => 'fa-binoculars','name' => 'fa binoculars'],
            ['icon' => 'fa-birthday-cake','name' => 'fa birthday cake'],
            ['icon' => 'fa-bitbucket','name' => 'fa bitbucket'],
            ['icon' => 'fa-bitbucket-square','name' => 'fa bitbucket square'],
            ['icon' => 'fa-bitcoin','name' => 'fa bitcoin'],
            ['icon' => 'fa-black-tie','name' => 'fa black tie'],
            ['icon' => 'fa-blind','name' => 'fa blind'],
            ['icon' => 'fa-bluetooth','name' => 'fa bluetooth'],
            ['icon' => 'fa-bluetooth-b','name' => 'fa bluetooth b'],
            ['icon' => 'fa-bold','name' => 'fa bold'],
            ['icon' => 'fa-bolt','name' => 'fa bolt'],
            ['icon' => 'fa-bomb','name' => 'fa bomb'],
            ['icon' => 'fa-book','name' => 'fa book'],
            ['icon' => 'fa-bookmark','name' => 'fa bookmark'],
            ['icon' => 'fa-bookmark-o','name' => 'fa bookmark o'],
            ['icon' => 'fa-braille','name' => 'fa braille'],
            ['icon' => 'fa-briefcase','name' => 'fa briefcase'],
            ['icon' => 'fa-btc','name' => 'fa btc'],
            ['icon' => 'fa-bug','name' => 'fa bug'],
            ['icon' => 'fa-building','name' => 'fa building'],
            ['icon' => 'fa-building-o','name' => 'fa building o'],
            ['icon' => 'fa-bullhorn','name' => 'fa bullhorn'],
            ['icon' => 'fa-bullseye','name' => 'fa bullseye'],
            ['icon' => 'fa-bus','name' => 'fa bus'],
            ['icon' => 'fa-buysellads','name' => 'fa buysellads'],
            ['icon' => 'fa-cab','name' => 'fa cab'],
            ['icon' => 'fa-calculator','name' => 'fa calculator'],
            ['icon' => 'fa-calendar','name' => 'fa calendar'],
            ['icon' => 'fa-calendar-check-o','name' => 'fa calendar check o'],
            ['icon' => 'fa-calendar-minus-o','name' => 'fa calendar minus o'],
            ['icon' => 'fa-calendar-o','name' => 'fa calendar o'],
            ['icon' => 'fa-calendar-plus-o','name' => 'fa calendar plus o'],
            ['icon' => 'fa-calendar-times-o','name' => 'fa calendar times o'],
            ['icon' => 'fa-camera','name' => 'fa camera'],
            ['icon' => 'fa-camera-retro','name' => 'fa camera retro'],
            ['icon' => 'fa-car','name' => 'fa car'],
            ['icon' => 'fa-caret-down','name' => 'fa caret down'],
            ['icon' => 'fa-caret-left','name' => 'fa caret left'],
            ['icon' => 'fa-caret-right','name' => 'fa caret right'],
            ['icon' => 'fa-caret-square-o-down','name' => 'fa caret square o down'],
            ['icon' => 'fa-caret-square-o-left','name' => 'fa caret square o left'],
            ['icon' => 'fa-caret-square-o-right','name' => 'fa caret square o right'],
            ['icon' => 'fa-caret-square-o-up','name' => 'fa caret square o up'],
            ['icon' => 'fa-caret-up','name' => 'fa caret up'],
            ['icon' => 'fa-cart-arrow-down','name' => 'fa cart arrow down'],
            ['icon' => 'fa-cart-plus','name' => 'fa cart plus'],
            ['icon' => 'fa-cc','name' => 'fa cc'],
            ['icon' => 'fa-cc-amex','name' => 'fa cc amex'],
            ['icon' => 'fa-cc-diners-club','name' => 'fa cc diners club'],
            ['icon' => 'fa-cc-discover','name' => 'fa cc discover'],
            ['icon' => 'fa-cc-jcb','name' => 'fa cc jcb'],
            ['icon' => 'fa-cc-mastercard','name' => 'fa cc mastercard'],
            ['icon' => 'fa-cc-paypal','name' => 'fa cc paypal'],
            ['icon' => 'fa-cc-stripe','name' => 'fa cc stripe'],
            ['icon' => 'fa-cc-visa','name' => 'fa cc visa'],
            ['icon' => 'fa-certificate','name' => 'fa certificate'],
            ['icon' => 'fa-chain','name' => 'fa chain'],
            ['icon' => 'fa-chain-broken','name' => 'fa chain broken'],
            ['icon' => 'fa-check','name' => 'fa check'],
            ['icon' => 'fa-check-circle','name' => 'fa check circle'],
            ['icon' => 'fa-check-circle-o','name' => 'fa check circle o'],
            ['icon' => 'fa-check-square','name' => 'fa check square'],
            ['icon' => 'fa-check-square-o','name' => 'fa check square o'],
            ['icon' => 'fa-chevron-circle-down','name' => 'fa chevron circle down'],
            ['icon' => 'fa-chevron-circle-left','name' => 'fa chevron circle left'],
            ['icon' => 'fa-chevron-circle-right','name' => 'fa chevron circle right'],
            ['icon' => 'fa-chevron-circle-up','name' => 'fa chevron circle up'],
            ['icon' => 'fa-chevron-down','name' => 'fa chevron down'],
            ['icon' => 'fa-chevron-left','name' => 'fa chevron left'],
            ['icon' => 'fa-chevron-right','name' => 'fa chevron right'],
            ['icon' => 'fa-chevron-up','name' => 'fa chevron up'],
            ['icon' => 'fa-child','name' => 'fa child'],
            ['icon' => 'fa-chrome','name' => 'fa chrome'],
            ['icon' => 'fa-circle','name' => 'fa circle'],
            ['icon' => 'fa-circle-o','name' => 'fa circle o'],
            ['icon' => 'fa-circle-o-notch','name' => 'fa circle o notch'],
            ['icon' => 'fa-circle-thin','name' => 'fa circle thin'],
            ['icon' => 'fa-clipboard','name' => 'fa clipboard'],
            ['icon' => 'fa-clock-o','name' => 'fa clock o'],
            ['icon' => 'fa-clone','name' => 'fa clone'],
            ['icon' => 'fa-close','name' => 'fa close'],
            ['icon' => 'fa-cloud','name' => 'fa cloud'],
            ['icon' => 'fa-cloud-download','name' => 'fa cloud download'],
            ['icon' => 'fa-cloud-upload','name' => 'fa cloud upload'],
            ['icon' => 'fa-cny','name' => 'fa cny'],
            ['icon' => 'fa-code','name' => 'fa code'],
            ['icon' => 'fa-code-fork','name' => 'fa code fork'],
            ['icon' => 'fa-codepen','name' => 'fa codepen'],
            ['icon' => 'fa-codiepie','name' => 'fa codiepie'],
            ['icon' => 'fa-coffee','name' => 'fa coffee'],
            ['icon' => 'fa-cog','name' => 'fa cog'],
            ['icon' => 'fa-cogs','name' => 'fa cogs'],
            ['icon' => 'fa-columns','name' => 'fa columns'],
            ['icon' => 'fa-comment','name' => 'fa comment'],
            ['icon' => 'fa-comment-o','name' => 'fa comment o'],
            ['icon' => 'fa-commenting','name' => 'fa commenting'],
            ['icon' => 'fa-commenting-o','name' => 'fa commenting o'],
            ['icon' => 'fa-comments','name' => 'fa comments'],
            ['icon' => 'fa-comments-o','name' => 'fa comments o'],
            ['icon' => 'fa-compass','name' => 'fa compass'],
            ['icon' => 'fa-compress','name' => 'fa compress'],
            ['icon' => 'fa-connectdevelop','name' => 'fa connectdevelop'],
            ['icon' => 'fa-contao','name' => 'fa contao'],
            ['icon' => 'fa-copy','name' => 'fa copy'],
            ['icon' => 'fa-copyright','name' => 'fa copyright'],
            ['icon' => 'fa-creative-commons','name' => 'fa creative commons'],
            ['icon' => 'fa-credit-card','name' => 'fa credit card'],
            ['icon' => 'fa-credit-card-alt','name' => 'fa credit card alt'],
            ['icon' => 'fa-crop','name' => 'fa crop'],
            ['icon' => 'fa-crosshairs','name' => 'fa crosshairs'],
            ['icon' => 'fa-css3','name' => 'fa css3'],
            ['icon' => 'fa-cube','name' => 'fa cube'],
            ['icon' => 'fa-cubes','name' => 'fa cubes'],
            ['icon' => 'fa-cut','name' => 'fa cut'],
            ['icon' => 'fa-cutlery','name' => 'fa cutlery'],
            ['icon' => 'fa-dashboard','name' => 'fa dashboard'],
            ['icon' => 'fa-dashcube','name' => 'fa dashcube'],
            ['icon' => 'fa-database','name' => 'fa database'],
            ['icon' => 'fa-deaf','name' => 'fa deaf'],
            ['icon' => 'fa-deafness','name' => 'fa deafness'],
            ['icon' => 'fa-dedent','name' => 'fa dedent'],
            ['icon' => 'fa-delicious','name' => 'fa delicious'],
            ['icon' => 'fa-desktop','name' => 'fa desktop'],
            ['icon' => 'fa-deviantart','name' => 'fa deviantart'],
            ['icon' => 'fa-diamond','name' => 'fa diamond'],
            ['icon' => 'fa-digg','name' => 'fa digg'],
            ['icon' => 'fa-dollar','name' => 'fa dollar'],
            ['icon' => 'fa-dot-circle-o','name' => 'fa dot circle o'],
            ['icon' => 'fa-download','name' => 'fa download'],
            ['icon' => 'fa-dribbble','name' => 'fa dribbble'],
            ['icon' => 'fa-drivers-license','name' => 'fa drivers license'],
            ['icon' => 'fa-drivers-license-o','name' => 'fa drivers license o'],
            ['icon' => 'fa-dropbox','name' => 'fa dropbox'],
            ['icon' => 'fa-drupal','name' => 'fa drupal'],
            ['icon' => 'fa-edge','name' => 'fa edge'],
            ['icon' => 'fa-edit','name' => 'fa edit'],
            ['icon' => 'fa-eercast','name' => 'fa eercast'],
            ['icon' => 'fa-eject','name' => 'fa eject'],
            ['icon' => 'fa-ellipsis-h','name' => 'fa ellipsis h'],
            ['icon' => 'fa-ellipsis-v','name' => 'fa ellipsis v'],
            ['icon' => 'fa-empire','name' => 'fa empire'],
            ['icon' => 'fa-envelope','name' => 'fa envelope'],
            ['icon' => 'fa-envelope-o','name' => 'fa envelope o'],
            ['icon' => 'fa-envelope-open','name' => 'fa envelope open'],
            ['icon' => 'fa-envelope-open-o','name' => 'fa envelope open o'],
            ['icon' => 'fa-envelope-square','name' => 'fa envelope square'],
            ['icon' => 'fa-envira','name' => 'fa envira'],
            ['icon' => 'fa-eraser','name' => 'fa eraser'],
            ['icon' => 'fa-etsy','name' => 'fa etsy'],
            ['icon' => 'fa-eur','name' => 'fa eur'],
            ['icon' => 'fa-euro','name' => 'fa euro'],
            ['icon' => 'fa-exchange','name' => 'fa exchange'],
            ['icon' => 'fa-exclamation','name' => 'fa exclamation'],
            ['icon' => 'fa-exclamation-circle','name' => 'fa exclamation circle'],
            ['icon' => 'fa-exclamation-triangle','name' => 'fa exclamation triangle'],
            ['icon' => 'fa-expand','name' => 'fa expand'],
            ['icon' => 'fa-expeditedssl','name' => 'fa expeditedssl'],
            ['icon' => 'fa-external-link','name' => 'fa external link'],
            ['icon' => 'fa-external-link-square','name' => 'fa external link square'],
            ['icon' => 'fa-eye','name' => 'fa eye'],
            ['icon' => 'fa-eye-slash','name' => 'fa eye slash'],
            ['icon' => 'fa-eyedropper','name' => 'fa eyedropper'],
            ['icon' => 'fa-fa','name' => 'fa fa'],
            ['icon' => 'fa-facebook','name' => 'fa facebook'],
            ['icon' => 'fa-facebook-f','name' => 'fa facebook f'],
            ['icon' => 'fa-facebook-official','name' => 'fa facebook official'],
            ['icon' => 'fa-facebook-square','name' => 'fa facebook square'],
            ['icon' => 'fa-fast-backward','name' => 'fa fast backward'],
            ['icon' => 'fa-fast-forward','name' => 'fa fast forward'],
            ['icon' => 'fa-fax','name' => 'fa fax'],
            ['icon' => 'fa-feed','name' => 'fa feed'],
            ['icon' => 'fa-female','name' => 'fa female'],
            ['icon' => 'fa-fighter-jet','name' => 'fa fighter jet'],
            ['icon' => 'fa-file','name' => 'fa file'],
            ['icon' => 'fa-file-archive-o','name' => 'fa file archive o'],
            ['icon' => 'fa-file-audio-o','name' => 'fa file audio o'],
            ['icon' => 'fa-file-code-o','name' => 'fa file code o'],
            ['icon' => 'fa-file-excel-o','name' => 'fa file excel o'],
            ['icon' => 'fa-file-image-o','name' => 'fa file image o'],
            ['icon' => 'fa-file-movie-o','name' => 'fa file movie o'],
            ['icon' => 'fa-file-o','name' => 'fa file o'],
            ['icon' => 'fa-file-pdf-o','name' => 'fa file pdf o'],
            ['icon' => 'fa-file-photo-o','name' => 'fa file photo o'],
            ['icon' => 'fa-file-picture-o','name' => 'fa file picture o'],
            ['icon' => 'fa-file-powerpoint-o','name' => 'fa file powerpoint o'],
            ['icon' => 'fa-file-sound-o','name' => 'fa file sound o'],
            ['icon' => 'fa-file-text','name' => 'fa file text'],
            ['icon' => 'fa-file-text-o','name' => 'fa file text o'],
            ['icon' => 'fa-file-video-o','name' => 'fa file video o'],
            ['icon' => 'fa-file-word-o','name' => 'fa file word o'],
            ['icon' => 'fa-file-zip-o','name' => 'fa file zip o'],
            ['icon' => 'fa-files-o','name' => 'fa files o'],
            ['icon' => 'fa-film','name' => 'fa film'],
            ['icon' => 'fa-filter','name' => 'fa filter'],
            ['icon' => 'fa-fire','name' => 'fa fire'],
            ['icon' => 'fa-fire-extinguisher','name' => 'fa fire extinguisher'],
            ['icon' => 'fa-firefox','name' => 'fa firefox'],
            ['icon' => 'fa-first-order','name' => 'fa first order'],
            ['icon' => 'fa-flag','name' => 'fa flag'],
            ['icon' => 'fa-flag-checkered','name' => 'fa flag checkered'],
            ['icon' => 'fa-flag-o','name' => 'fa flag o'],
            ['icon' => 'fa-flash','name' => 'fa flash'],
            ['icon' => 'fa-flask','name' => 'fa flask'],
            ['icon' => 'fa-flickr','name' => 'fa flickr'],
            ['icon' => 'fa-floppy-o','name' => 'fa floppy o'],
            ['icon' => 'fa-folder','name' => 'fa folder'],
            ['icon' => 'fa-folder-o','name' => 'fa folder o'],
            ['icon' => 'fa-folder-open','name' => 'fa folder open'],
            ['icon' => 'fa-folder-open-o','name' => 'fa folder open o'],
            ['icon' => 'fa-font','name' => 'fa font'],
            ['icon' => 'fa-font-awesome','name' => 'fa font awesome'],
            ['icon' => 'fa-fonticons','name' => 'fa fonticons'],
            ['icon' => 'fa-fort-awesome','name' => 'fa fort awesome'],
            ['icon' => 'fa-forumbee','name' => 'fa forumbee'],
            ['icon' => 'fa-forward','name' => 'fa forward'],
            ['icon' => 'fa-foursquare','name' => 'fa foursquare'],
            ['icon' => 'fa-free-code-camp','name' => 'fa free code camp'],
            ['icon' => 'fa-frown-o','name' => 'fa frown o'],
            ['icon' => 'fa-futbol-o','name' => 'fa futbol o'],
            ['icon' => 'fa-gamepad','name' => 'fa gamepad'],
            ['icon' => 'fa-gavel','name' => 'fa gavel'],
            ['icon' => 'fa-gbp','name' => 'fa gbp'],
            ['icon' => 'fa-ge','name' => 'fa ge'],
            ['icon' => 'fa-gear','name' => 'fa gear'],
            ['icon' => 'fa-gears','name' => 'fa gears'],
            ['icon' => 'fa-genderless','name' => 'fa genderless'],
            ['icon' => 'fa-get-pocket','name' => 'fa get pocket'],
            ['icon' => 'fa-gg','name' => 'fa gg'],
            ['icon' => 'fa-gg-circle','name' => 'fa gg circle'],
            ['icon' => 'fa-gift','name' => 'fa gift'],
            ['icon' => 'fa-git','name' => 'fa git'],
            ['icon' => 'fa-git-square','name' => 'fa git square'],
            ['icon' => 'fa-github','name' => 'fa github'],
            ['icon' => 'fa-github-alt','name' => 'fa github alt'],
            ['icon' => 'fa-github-square','name' => 'fa github square'],
            ['icon' => 'fa-gitlab','name' => 'fa gitlab'],
            ['icon' => 'fa-gittip','name' => 'fa gittip'],
            ['icon' => 'fa-glass','name' => 'fa glass'],
            ['icon' => 'fa-glide','name' => 'fa glide'],
            ['icon' => 'fa-glide-g','name' => 'fa glide g'],
            ['icon' => 'fa-globe','name' => 'fa globe'],
            ['icon' => 'fa-google','name' => 'fa google'],
            ['icon' => 'fa-google-plus','name' => 'fa google plus'],
            ['icon' => 'fa-google-plus-circle','name' => 'fa google plus circle'],
            ['icon' => 'fa-google-plus-official','name' => 'fa google plus official'],
            ['icon' => 'fa-google-plus-square','name' => 'fa google plus square'],
            ['icon' => 'fa-google-wallet','name' => 'fa google wallet'],
            ['icon' => 'fa-graduation-cap','name' => 'fa graduation cap'],
            ['icon' => 'fa-gratipay','name' => 'fa gratipay'],
            ['icon' => 'fa-grav','name' => 'fa grav'],
            ['icon' => 'fa-group','name' => 'fa group'],
            ['icon' => 'fa-h-square','name' => 'fa h square'],
            ['icon' => 'fa-hacker-news','name' => 'fa hacker news'],
            ['icon' => 'fa-hand-grab-o','name' => 'fa hand grab o'],
            ['icon' => 'fa-hand-lizard-o','name' => 'fa hand lizard o'],
            ['icon' => 'fa-hand-o-down','name' => 'fa hand o down'],
            ['icon' => 'fa-hand-o-left','name' => 'fa hand o left'],
            ['icon' => 'fa-hand-o-right','name' => 'fa hand o right'],
            ['icon' => 'fa-hand-o-up','name' => 'fa hand o up'],
            ['icon' => 'fa-hand-paper-o','name' => 'fa hand paper o'],
            ['icon' => 'fa-hand-peace-o','name' => 'fa hand peace o'],
            ['icon' => 'fa-hand-pointer-o','name' => 'fa hand pointer o'],
            ['icon' => 'fa-hand-rock-o','name' => 'fa hand rock o'],
            ['icon' => 'fa-hand-scissors-o','name' => 'fa hand scissors o'],
            ['icon' => 'fa-hand-spock-o','name' => 'fa hand spock o'],
            ['icon' => 'fa-hand-stop-o','name' => 'fa hand stop o'],
            ['icon' => 'fa-handshake-o','name' => 'fa handshake o'],
            ['icon' => 'fa-hard-of-hearing','name' => 'fa hard of hearing'],
            ['icon' => 'fa-hashtag','name' => 'fa hashtag'],
            ['icon' => 'fa-hdd-o','name' => 'fa hdd o'],
            ['icon' => 'fa-header','name' => 'fa header'],
            ['icon' => 'fa-headphones','name' => 'fa headphones'],
            ['icon' => 'fa-heart','name' => 'fa heart'],
            ['icon' => 'fa-heart-o','name' => 'fa heart o'],
            ['icon' => 'fa-heartbeat','name' => 'fa heartbeat'],
            ['icon' => 'fa-history','name' => 'fa history'],
            ['icon' => 'fa-home','name' => 'fa home'],
            ['icon' => 'fa-hospital-o','name' => 'fa hospital o'],
            ['icon' => 'fa-hotel','name' => 'fa hotel'],
            ['icon' => 'fa-hourglass','name' => 'fa hourglass'],
            ['icon' => 'fa-hourglass-1','name' => 'fa hourglass 1'],
            ['icon' => 'fa-hourglass-2','name' => 'fa hourglass 2'],
            ['icon' => 'fa-hourglass-3','name' => 'fa hourglass 3'],
            ['icon' => 'fa-hourglass-end','name' => 'fa hourglass end'],
            ['icon' => 'fa-hourglass-half','name' => 'fa hourglass half'],
            ['icon' => 'fa-hourglass-o','name' => 'fa hourglass o'],
            ['icon' => 'fa-hourglass-start','name' => 'fa hourglass start'],
            ['icon' => 'fa-houzz','name' => 'fa houzz'],
            ['icon' => 'fa-html5','name' => 'fa html5'],
            ['icon' => 'fa-i-cursor','name' => 'fa i cursor'],
            ['icon' => 'fa-id-badge','name' => 'fa id badge'],
            ['icon' => 'fa-id-card','name' => 'fa id card'],
            ['icon' => 'fa-id-card-o','name' => 'fa id card o'],
            ['icon' => 'fa-ils','name' => 'fa ils'],
            ['icon' => 'fa-image','name' => 'fa image'],
            ['icon' => 'fa-imdb','name' => 'fa imdb'],
            ['icon' => 'fa-inbox','name' => 'fa inbox'],
            ['icon' => 'fa-indent','name' => 'fa indent'],
            ['icon' => 'fa-industry','name' => 'fa industry'],
            ['icon' => 'fa-info','name' => 'fa info'],
            ['icon' => 'fa-info-circle','name' => 'fa info circle'],
            ['icon' => 'fa-inr','name' => 'fa inr'],
            ['icon' => 'fa-instagram','name' => 'fa instagram'],
            ['icon' => 'fa-institution','name' => 'fa institution'],
            ['icon' => 'fa-internet-explorer','name' => 'fa internet explorer'],
            ['icon' => 'fa-intersex','name' => 'fa intersex'],
            ['icon' => 'fa-ioxhost','name' => 'fa ioxhost'],
            ['icon' => 'fa-italic','name' => 'fa italic'],
            ['icon' => 'fa-joomla','name' => 'fa joomla'],
            ['icon' => 'fa-jpy','name' => 'fa jpy'],
            ['icon' => 'fa-jsfiddle','name' => 'fa jsfiddle'],
            ['icon' => 'fa-key','name' => 'fa key'],
            ['icon' => 'fa-keyboard-o','name' => 'fa keyboard o'],
            ['icon' => 'fa-krw','name' => 'fa krw'],
            ['icon' => 'fa-language','name' => 'fa language'],
            ['icon' => 'fa-laptop','name' => 'fa laptop'],
            ['icon' => 'fa-lastfm','name' => 'fa lastfm'],
            ['icon' => 'fa-lastfm-square','name' => 'fa lastfm square'],
            ['icon' => 'fa-leaf','name' => 'fa leaf'],
            ['icon' => 'fa-leanpub','name' => 'fa leanpub'],
            ['icon' => 'fa-legal','name' => 'fa legal'],
            ['icon' => 'fa-lemon-o','name' => 'fa lemon o'],
            ['icon' => 'fa-level-down','name' => 'fa level down'],
            ['icon' => 'fa-level-up','name' => 'fa level up'],
            ['icon' => 'fa-life-bouy','name' => 'fa life bouy'],
            ['icon' => 'fa-life-buoy','name' => 'fa life buoy'],
            ['icon' => 'fa-life-ring','name' => 'fa life ring'],
            ['icon' => 'fa-life-saver','name' => 'fa life saver'],
            ['icon' => 'fa-lightbulb-o','name' => 'fa lightbulb o'],
            ['icon' => 'fa-line-chart','name' => 'fa line chart'],
            ['icon' => 'fa-link','name' => 'fa link'],
            ['icon' => 'fa-linkedin','name' => 'fa linkedin'],
            ['icon' => 'fa-linkedin-square','name' => 'fa linkedin square'],
            ['icon' => 'fa-linode','name' => 'fa linode'],
            ['icon' => 'fa-linux','name' => 'fa linux'],
            ['icon' => 'fa-list','name' => 'fa list'],
            ['icon' => 'fa-list-alt','name' => 'fa list alt'],
            ['icon' => 'fa-list-ol','name' => 'fa list ol'],
            ['icon' => 'fa-list-ul','name' => 'fa list ul'],
            ['icon' => 'fa-location-arrow','name' => 'fa location arrow'],
            ['icon' => 'fa-lock','name' => 'fa lock'],
            ['icon' => 'fa-long-arrow-down','name' => 'fa long arrow down'],
            ['icon' => 'fa-long-arrow-left','name' => 'fa long arrow left'],
            ['icon' => 'fa-long-arrow-right','name' => 'fa long arrow right'],
            ['icon' => 'fa-long-arrow-up','name' => 'fa long arrow up'],
            ['icon' => 'fa-low-vision','name' => 'fa low vision'],
            ['icon' => 'fa-magic','name' => 'fa magic'],
            ['icon' => 'fa-magnet','name' => 'fa magnet'],
            ['icon' => 'fa-mail-forward','name' => 'fa mail forward'],
            ['icon' => 'fa-mail-reply','name' => 'fa mail reply'],
            ['icon' => 'fa-mail-reply-all','name' => 'fa mail reply all'],
            ['icon' => 'fa-male','name' => 'fa male'],
            ['icon' => 'fa-map','name' => 'fa map'],
            ['icon' => 'fa-map-marker','name' => 'fa map marker'],
            ['icon' => 'fa-map-o','name' => 'fa map o'],
            ['icon' => 'fa-map-pin','name' => 'fa map pin'],
            ['icon' => 'fa-map-signs','name' => 'fa map signs'],
            ['icon' => 'fa-mars','name' => 'fa mars'],
            ['icon' => 'fa-mars-double','name' => 'fa mars double'],
            ['icon' => 'fa-mars-stroke','name' => 'fa mars stroke'],
            ['icon' => 'fa-mars-stroke-h','name' => 'fa mars stroke h'],
            ['icon' => 'fa-mars-stroke-v','name' => 'fa mars stroke v'],
            ['icon' => 'fa-maxcdn','name' => 'fa maxcdn'],
            ['icon' => 'fa-meanpath','name' => 'fa meanpath'],
            ['icon' => 'fa-medium','name' => 'fa medium'],
            ['icon' => 'fa-medkit','name' => 'fa medkit'],
            ['icon' => 'fa-meetup','name' => 'fa meetup'],
            ['icon' => 'fa-meh-o','name' => 'fa meh o'],
            ['icon' => 'fa-mercury','name' => 'fa mercury'],
            ['icon' => 'fa-microchip','name' => 'fa microchip'],
            ['icon' => 'fa-microphone','name' => 'fa microphone'],
            ['icon' => 'fa-microphone-slash','name' => 'fa microphone slash'],
            ['icon' => 'fa-minus','name' => 'fa minus'],
            ['icon' => 'fa-minus-circle','name' => 'fa minus circle'],
            ['icon' => 'fa-minus-square','name' => 'fa minus square'],
            ['icon' => 'fa-minus-square-o','name' => 'fa minus square o'],
            ['icon' => 'fa-mixcloud','name' => 'fa mixcloud'],
            ['icon' => 'fa-mobile','name' => 'fa mobile'],
            ['icon' => 'fa-mobile-phone','name' => 'fa mobile phone'],
            ['icon' => 'fa-modx','name' => 'fa modx'],
            ['icon' => 'fa-money','name' => 'fa money'],
            ['icon' => 'fa-moon-o','name' => 'fa moon o'],
            ['icon' => 'fa-mortar-board','name' => 'fa mortar board'],
            ['icon' => 'fa-motorcycle','name' => 'fa motorcycle'],
            ['icon' => 'fa-mouse-pointer','name' => 'fa mouse pointer'],
            ['icon' => 'fa-music','name' => 'fa music'],
            ['icon' => 'fa-navicon','name' => 'fa navicon'],
            ['icon' => 'fa-neuter','name' => 'fa neuter'],
            ['icon' => 'fa-newspaper-o','name' => 'fa newspaper o'],
            ['icon' => 'fa-object-group','name' => 'fa object group'],
            ['icon' => 'fa-object-ungroup','name' => 'fa object ungroup'],
            ['icon' => 'fa-odnoklassniki','name' => 'fa odnoklassniki'],
            ['icon' => 'fa-odnoklassniki-square','name' => 'fa odnoklassniki square'],
            ['icon' => 'fa-opencart','name' => 'fa opencart'],
            ['icon' => 'fa-openid','name' => 'fa openid'],
            ['icon' => 'fa-opera','name' => 'fa opera'],
            ['icon' => 'fa-optin-monster','name' => 'fa optin monster'],
            ['icon' => 'fa-outdent','name' => 'fa outdent'],
            ['icon' => 'fa-pagelines','name' => 'fa pagelines'],
            ['icon' => 'fa-paint-brush','name' => 'fa paint brush'],
            ['icon' => 'fa-paper-plane','name' => 'fa paper plane'],
            ['icon' => 'fa-paper-plane-o','name' => 'fa paper plane o'],
            ['icon' => 'fa-paperclip','name' => 'fa paperclip'],
            ['icon' => 'fa-paragraph','name' => 'fa paragraph'],
            ['icon' => 'fa-paste','name' => 'fa paste'],
            ['icon' => 'fa-pause','name' => 'fa pause'],
            ['icon' => 'fa-pause-circle','name' => 'fa pause circle'],
            ['icon' => 'fa-pause-circle-o','name' => 'fa pause circle o'],
            ['icon' => 'fa-paw','name' => 'fa paw'],
            ['icon' => 'fa-paypal','name' => 'fa paypal'],
            ['icon' => 'fa-pencil','name' => 'fa pencil'],
            ['icon' => 'fa-pencil-square','name' => 'fa pencil square'],
            ['icon' => 'fa-pencil-square-o','name' => 'fa pencil square o'],
            ['icon' => 'fa-percent','name' => 'fa percent'],
            ['icon' => 'fa-phone','name' => 'fa phone'],
            ['icon' => 'fa-phone-square','name' => 'fa phone square'],
            ['icon' => 'fa-photo','name' => 'fa photo'],
            ['icon' => 'fa-picture-o','name' => 'fa picture o'],
            ['icon' => 'fa-pie-chart','name' => 'fa pie chart'],
            ['icon' => 'fa-pied-piper','name' => 'fa pied piper'],
            ['icon' => 'fa-pied-piper-alt','name' => 'fa pied piper alt'],
            ['icon' => 'fa-pied-piper-pp','name' => 'fa pied piper pp'],
            ['icon' => 'fa-pinterest','name' => 'fa pinterest'],
            ['icon' => 'fa-pinterest-p','name' => 'fa pinterest p'],
            ['icon' => 'fa-pinterest-square','name' => 'fa pinterest square'],
            ['icon' => 'fa-plane','name' => 'fa plane'],
            ['icon' => 'fa-play','name' => 'fa play'],
            ['icon' => 'fa-play-circle','name' => 'fa play circle'],
            ['icon' => 'fa-play-circle-o','name' => 'fa play circle o'],
            ['icon' => 'fa-plug','name' => 'fa plug'],
            ['icon' => 'fa-plus','name' => 'fa plus'],
            ['icon' => 'fa-plus-circle','name' => 'fa plus circle'],
            ['icon' => 'fa-plus-square','name' => 'fa plus square'],
            ['icon' => 'fa-plus-square-o','name' => 'fa plus square o'],
            ['icon' => 'fa-podcast','name' => 'fa podcast'],
            ['icon' => 'fa-power-off','name' => 'fa power off'],
            ['icon' => 'fa-print','name' => 'fa print'],
            ['icon' => 'fa-product-hunt','name' => 'fa product hunt'],
            ['icon' => 'fa-puzzle-piece','name' => 'fa puzzle piece'],
            ['icon' => 'fa-qq','name' => 'fa qq'],
            ['icon' => 'fa-qrcode','name' => 'fa qrcode'],
            ['icon' => 'fa-question','name' => 'fa question'],
            ['icon' => 'fa-question-circle','name' => 'fa question circle'],
            ['icon' => 'fa-question-circle-o','name' => 'fa question circle o'],
            ['icon' => 'fa-quora','name' => 'fa quora'],
            ['icon' => 'fa-quote-left','name' => 'fa quote left'],
            ['icon' => 'fa-quote-right','name' => 'fa quote right'],
            ['icon' => 'fa-ra','name' => 'fa ra'],
            ['icon' => 'fa-random','name' => 'fa random'],
            ['icon' => 'fa-ravelry','name' => 'fa ravelry'],
            ['icon' => 'fa-rebel','name' => 'fa rebel'],
            ['icon' => 'fa-recycle','name' => 'fa recycle'],
            ['icon' => 'fa-reddit','name' => 'fa reddit'],
            ['icon' => 'fa-reddit-alien','name' => 'fa reddit alien'],
            ['icon' => 'fa-reddit-square','name' => 'fa reddit square'],
            ['icon' => 'fa-refresh','name' => 'fa refresh'],
            ['icon' => 'fa-registered','name' => 'fa registered'],
            ['icon' => 'fa-remove','name' => 'fa remove'],
            ['icon' => 'fa-renren','name' => 'fa renren'],
            ['icon' => 'fa-reorder','name' => 'fa reorder'],
            ['icon' => 'fa-repeat','name' => 'fa repeat'],
            ['icon' => 'fa-reply','name' => 'fa reply'],
            ['icon' => 'fa-reply-all','name' => 'fa reply all'],
            ['icon' => 'fa-resistance','name' => 'fa resistance'],
            ['icon' => 'fa-retweet','name' => 'fa retweet'],
            ['icon' => 'fa-rmb','name' => 'fa rmb'],
            ['icon' => 'fa-road','name' => 'fa road'],
            ['icon' => 'fa-rocket','name' => 'fa rocket'],
            ['icon' => 'fa-rotate-left','name' => 'fa rotate left'],
            ['icon' => 'fa-rotate-right','name' => 'fa rotate right'],
            ['icon' => 'fa-rouble','name' => 'fa rouble'],
            ['icon' => 'fa-rss','name' => 'fa rss'],
            ['icon' => 'fa-rss-square','name' => 'fa rss square'],
            ['icon' => 'fa-rub','name' => 'fa rub'],
            ['icon' => 'fa-ruble','name' => 'fa ruble'],
            ['icon' => 'fa-rupee','name' => 'fa rupee'],
            ['icon' => 'fa-s15','name' => 'fa s15'],
            ['icon' => 'fa-safari','name' => 'fa safari'],
            ['icon' => 'fa-save','name' => 'fa save'],
            ['icon' => 'fa-scissors','name' => 'fa scissors'],
            ['icon' => 'fa-scribd','name' => 'fa scribd'],
            ['icon' => 'fa-search','name' => 'fa search'],
            ['icon' => 'fa-search-minus','name' => 'fa search minus'],
            ['icon' => 'fa-search-plus','name' => 'fa search plus'],
            ['icon' => 'fa-sellsy','name' => 'fa sellsy'],
            ['icon' => 'fa-send','name' => 'fa send'],
            ['icon' => 'fa-send-o','name' => 'fa send o'],
            ['icon' => 'fa-server','name' => 'fa server'],
            ['icon' => 'fa-share','name' => 'fa share'],
            ['icon' => 'fa-share-alt','name' => 'fa share alt'],
            ['icon' => 'fa-share-alt-square','name' => 'fa share alt square'],
            ['icon' => 'fa-share-square','name' => 'fa share square'],
            ['icon' => 'fa-share-square-o','name' => 'fa share square o'],
            ['icon' => 'fa-shekel','name' => 'fa shekel'],
            ['icon' => 'fa-sheqel','name' => 'fa sheqel'],
            ['icon' => 'fa-shield','name' => 'fa shield'],
            ['icon' => 'fa-ship','name' => 'fa ship'],
            ['icon' => 'fa-shirtsinbulk','name' => 'fa shirtsinbulk'],
            ['icon' => 'fa-shopping-bag','name' => 'fa shopping bag'],
            ['icon' => 'fa-shopping-basket','name' => 'fa shopping basket'],
            ['icon' => 'fa-shopping-cart','name' => 'fa shopping cart'],
            ['icon' => 'fa-shower','name' => 'fa shower'],
            ['icon' => 'fa-sign-in','name' => 'fa sign in'],
            ['icon' => 'fa-sign-language','name' => 'fa sign language'],
            ['icon' => 'fa-sign-out','name' => 'fa sign out'],
            ['icon' => 'fa-signal','name' => 'fa signal'],
            ['icon' => 'fa-signing','name' => 'fa signing'],
            ['icon' => 'fa-simplybuilt','name' => 'fa simplybuilt'],
            ['icon' => 'fa-sitemap','name' => 'fa sitemap'],
            ['icon' => 'fa-skyatlas','name' => 'fa skyatlas'],
            ['icon' => 'fa-skype','name' => 'fa skype'],
            ['icon' => 'fa-slack','name' => 'fa slack'],
            ['icon' => 'fa-sliders','name' => 'fa sliders'],
            ['icon' => 'fa-slideshare','name' => 'fa slideshare'],
            ['icon' => 'fa-smile-o','name' => 'fa smile o'],
            ['icon' => 'fa-snapchat','name' => 'fa snapchat'],
            ['icon' => 'fa-snapchat-ghost','name' => 'fa snapchat ghost'],
            ['icon' => 'fa-snapchat-square','name' => 'fa snapchat square'],
            ['icon' => 'fa-snowflake-o','name' => 'fa snowflake o'],
            ['icon' => 'fa-soccer-ball-o','name' => 'fa soccer ball o'],
            ['icon' => 'fa-sort','name' => 'fa sort'],
            ['icon' => 'fa-sort-alpha-asc','name' => 'fa sort alpha asc'],
            ['icon' => 'fa-sort-alpha-desc','name' => 'fa sort alpha desc'],
            ['icon' => 'fa-sort-amount-asc','name' => 'fa sort amount asc'],
            ['icon' => 'fa-sort-amount-desc','name' => 'fa sort amount desc'],
            ['icon' => 'fa-sort-asc','name' => 'fa sort asc'],
            ['icon' => 'fa-sort-desc','name' => 'fa sort desc'],
            ['icon' => 'fa-sort-down','name' => 'fa sort down'],
            ['icon' => 'fa-sort-numeric-asc','name' => 'fa sort numeric asc'],
            ['icon' => 'fa-sort-numeric-desc','name' => 'fa sort numeric desc'],
            ['icon' => 'fa-sort-up','name' => 'fa sort up'],
            ['icon' => 'fa-soundcloud','name' => 'fa soundcloud'],
            ['icon' => 'fa-space-shuttle','name' => 'fa space shuttle'],
            ['icon' => 'fa-spinner','name' => 'fa spinner'],
            ['icon' => 'fa-spoon','name' => 'fa spoon'],
            ['icon' => 'fa-spotify','name' => 'fa spotify'],
            ['icon' => 'fa-square','name' => 'fa square'],
            ['icon' => 'fa-square-o','name' => 'fa square o'],
            ['icon' => 'fa-stack-exchange','name' => 'fa stack exchange'],
            ['icon' => 'fa-stack-overflow','name' => 'fa stack overflow'],
            ['icon' => 'fa-star','name' => 'fa star'],
            ['icon' => 'fa-star-half','name' => 'fa star half'],
            ['icon' => 'fa-star-half-empty','name' => 'fa star half empty'],
            ['icon' => 'fa-star-half-full','name' => 'fa star half full'],
            ['icon' => 'fa-star-half-o','name' => 'fa star half o'],
            ['icon' => 'fa-star-o','name' => 'fa star o'],
            ['icon' => 'fa-steam','name' => 'fa steam'],
            ['icon' => 'fa-steam-square','name' => 'fa steam square'],
            ['icon' => 'fa-step-backward','name' => 'fa step backward'],
            ['icon' => 'fa-step-forward','name' => 'fa step forward'],
            ['icon' => 'fa-stethoscope','name' => 'fa stethoscope'],
            ['icon' => 'fa-sticky-note','name' => 'fa sticky note'],
            ['icon' => 'fa-sticky-note-o','name' => 'fa sticky note o'],
            ['icon' => 'fa-stop','name' => 'fa stop'],
            ['icon' => 'fa-stop-circle','name' => 'fa stop circle'],
            ['icon' => 'fa-stop-circle-o','name' => 'fa stop circle o'],
            ['icon' => 'fa-street-view','name' => 'fa street view'],
            ['icon' => 'fa-strikethrough','name' => 'fa strikethrough'],
            ['icon' => 'fa-stumbleupon','name' => 'fa stumbleupon'],
            ['icon' => 'fa-stumbleupon-circle','name' => 'fa stumbleupon circle'],
            ['icon' => 'fa-subscript','name' => 'fa subscript'],
            ['icon' => 'fa-subway','name' => 'fa subway'],
            ['icon' => 'fa-suitcase','name' => 'fa suitcase'],
            ['icon' => 'fa-sun-o','name' => 'fa sun o'],
            ['icon' => 'fa-superpowers','name' => 'fa superpowers'],
            ['icon' => 'fa-superscript','name' => 'fa superscript'],
            ['icon' => 'fa-support','name' => 'fa support'],
            ['icon' => 'fa-table','name' => 'fa table'],
            ['icon' => 'fa-tablet','name' => 'fa tablet'],
            ['icon' => 'fa-tachometer','name' => 'fa tachometer'],
            ['icon' => 'fa-tag','name' => 'fa tag'],
            ['icon' => 'fa-tags','name' => 'fa tags'],
            ['icon' => 'fa-tasks','name' => 'fa tasks'],
            ['icon' => 'fa-taxi','name' => 'fa taxi'],
            ['icon' => 'fa-telegram','name' => 'fa telegram'],
            ['icon' => 'fa-television','name' => 'fa television'],
            ['icon' => 'fa-tencent-weibo','name' => 'fa tencent weibo'],
            ['icon' => 'fa-terminal','name' => 'fa terminal'],
            ['icon' => 'fa-text-height','name' => 'fa text height'],
            ['icon' => 'fa-text-width','name' => 'fa text width'],
            ['icon' => 'fa-th','name' => 'fa th'],
            ['icon' => 'fa-th-large','name' => 'fa th large'],
            ['icon' => 'fa-th-list','name' => 'fa th list'],
            ['icon' => 'fa-themeisle','name' => 'fa themeisle'],
            ['icon' => 'fa-thermometer','name' => 'fa thermometer'],
            ['icon' => 'fa-thermometer-0','name' => 'fa thermometer 0'],
            ['icon' => 'fa-thermometer-1','name' => 'fa thermometer 1'],
            ['icon' => 'fa-thermometer-2','name' => 'fa thermometer 2'],
            ['icon' => 'fa-thermometer-3','name' => 'fa thermometer 3'],
            ['icon' => 'fa-thermometer-4','name' => 'fa thermometer 4'],
            ['icon' => 'fa-thermometer-empty','name' => 'fa thermometer empty'],
            ['icon' => 'fa-thermometer-full','name' => 'fa thermometer full'],
            ['icon' => 'fa-thermometer-half','name' => 'fa thermometer half'],
            ['icon' => 'fa-thermometer-quarter','name' => 'fa thermometer quarter'],
            ['icon' => 'fa-thermometer-three-quarters','name' => 'fa thermometer three quarters'],
            ['icon' => 'fa-thumb-tack','name' => 'fa thumb tack'],
            ['icon' => 'fa-thumbs-down','name' => 'fa thumbs down'],
            ['icon' => 'fa-thumbs-o-down','name' => 'fa thumbs o down'],
            ['icon' => 'fa-thumbs-o-up','name' => 'fa thumbs o up'],
            ['icon' => 'fa-thumbs-up','name' => 'fa thumbs up'],
            ['icon' => 'fa-ticket','name' => 'fa ticket'],
            ['icon' => 'fa-times','name' => 'fa times'],
            ['icon' => 'fa-times-circle','name' => 'fa times circle'],
            ['icon' => 'fa-times-circle-o','name' => 'fa times circle o'],
            ['icon' => 'fa-times-rectangle','name' => 'fa times rectangle'],
            ['icon' => 'fa-times-rectangle-o','name' => 'fa times rectangle o'],
            ['icon' => 'fa-tint','name' => 'fa tint'],
            ['icon' => 'fa-toggle-down','name' => 'fa toggle down'],
            ['icon' => 'fa-toggle-left','name' => 'fa toggle left'],
            ['icon' => 'fa-toggle-off','name' => 'fa toggle off'],
            ['icon' => 'fa-toggle-on','name' => 'fa toggle on'],
            ['icon' => 'fa-toggle-right','name' => 'fa toggle right'],
            ['icon' => 'fa-toggle-up','name' => 'fa toggle up'],
            ['icon' => 'fa-trademark','name' => 'fa trademark'],
            ['icon' => 'fa-train','name' => 'fa train'],
            ['icon' => 'fa-transgender','name' => 'fa transgender'],
            ['icon' => 'fa-transgender-alt','name' => 'fa transgender alt'],
            ['icon' => 'fa-trash','name' => 'fa trash'],
            ['icon' => 'fa-trash-o','name' => 'fa trash o'],
            ['icon' => 'fa-tree','name' => 'fa tree'],
            ['icon' => 'fa-trello','name' => 'fa trello'],
            ['icon' => 'fa-tripadvisor','name' => 'fa tripadvisor'],
            ['icon' => 'fa-trophy','name' => 'fa trophy'],
            ['icon' => 'fa-truck','name' => 'fa truck'],
            ['icon' => 'fa-try','name' => 'fa try'],
            ['icon' => 'fa-tty','name' => 'fa tty'],
            ['icon' => 'fa-tumblr','name' => 'fa tumblr'],
            ['icon' => 'fa-tumblr-square','name' => 'fa tumblr square'],
            ['icon' => 'fa-turkish-lira','name' => 'fa turkish lira'],
            ['icon' => 'fa-tv','name' => 'fa tv'],
            ['icon' => 'fa-twitch','name' => 'fa twitch'],
            ['icon' => 'fa-twitter','name' => 'fa twitter'],
            ['icon' => 'fa-twitter-square','name' => 'fa twitter square'],
            ['icon' => 'fa-umbrella','name' => 'fa umbrella'],
            ['icon' => 'fa-underline','name' => 'fa underline'],
            ['icon' => 'fa-undo','name' => 'fa undo'],
            ['icon' => 'fa-universal-access','name' => 'fa universal access'],
            ['icon' => 'fa-university','name' => 'fa university'],
            ['icon' => 'fa-unlink','name' => 'fa unlink'],
            ['icon' => 'fa-unlock','name' => 'fa unlock'],
            ['icon' => 'fa-unlock-alt','name' => 'fa unlock alt'],
            ['icon' => 'fa-unsorted','name' => 'fa unsorted'],
            ['icon' => 'fa-upload','name' => 'fa upload'],
            ['icon' => 'fa-usb','name' => 'fa usb'],
            ['icon' => 'fa-usd','name' => 'fa usd'],
            ['icon' => 'fa-user','name' => 'fa user'],
            ['icon' => 'fa-user-circle','name' => 'fa user circle'],
            ['icon' => 'fa-user-circle-o','name' => 'fa user circle o'],
            ['icon' => 'fa-user-md','name' => 'fa user md'],
            ['icon' => 'fa-user-o','name' => 'fa user o'],
            ['icon' => 'fa-user-plus','name' => 'fa user plus'],
            ['icon' => 'fa-user-secret','name' => 'fa user secret'],
            ['icon' => 'fa-user-times','name' => 'fa user times'],
            ['icon' => 'fa-users','name' => 'fa users'],
            ['icon' => 'fa-vcard','name' => 'fa vcard'],
            ['icon' => 'fa-vcard-o','name' => 'fa vcard o'],
            ['icon' => 'fa-venus','name' => 'fa venus'],
            ['icon' => 'fa-venus-double','name' => 'fa venus double'],
            ['icon' => 'fa-venus-mars','name' => 'fa venus mars'],
            ['icon' => 'fa-viacoin','name' => 'fa viacoin'],
            ['icon' => 'fa-viadeo','name' => 'fa viadeo'],
            ['icon' => 'fa-viadeo-square','name' => 'fa viadeo square'],
            ['icon' => 'fa-video-camera','name' => 'fa video camera'],
            ['icon' => 'fa-vimeo','name' => 'fa vimeo'],
            ['icon' => 'fa-vimeo-square','name' => 'fa vimeo square'],
            ['icon' => 'fa-vine','name' => 'fa vine'],
            ['icon' => 'fa-vk','name' => 'fa vk'],
            ['icon' => 'fa-volume-control-phone','name' => 'fa volume control phone'],
            ['icon' => 'fa-volume-down','name' => 'fa volume down'],
            ['icon' => 'fa-volume-off','name' => 'fa volume off'],
            ['icon' => 'fa-volume-up','name' => 'fa volume up'],
            ['icon' => 'fa-warning','name' => 'fa warning'],
            ['icon' => 'fa-wechat','name' => 'fa wechat'],
            ['icon' => 'fa-weibo','name' => 'fa weibo'],
            ['icon' => 'fa-weixin','name' => 'fa weixin'],
            ['icon' => 'fa-whatsapp','name' => 'fa whatsapp'],
            ['icon' => 'fa-wheelchair','name' => 'fa wheelchair'],
            ['icon' => 'fa-wheelchair-alt','name' => 'fa wheelchair alt'],
            ['icon' => 'fa-wifi','name' => 'fa wifi'],
            ['icon' => 'fa-wikipedia-w','name' => 'fa wikipedia w'],
            ['icon' => 'fa-window-close','name' => 'fa window close'],
            ['icon' => 'fa-window-close-o','name' => 'fa window close o'],
            ['icon' => 'fa-window-maximize','name' => 'fa window maximize'],
            ['icon' => 'fa-window-minimize','name' => 'fa window minimize'],
            ['icon' => 'fa-window-restore','name' => 'fa window restore'],
            ['icon' => 'fa-windows','name' => 'fa windows'],
            ['icon' => 'fa-won','name' => 'fa won'],
            ['icon' => 'fa-wordpress','name' => 'fa wordpress'],
            ['icon' => 'fa-wpbeginner','name' => 'fa wpbeginner'],
            ['icon' => 'fa-wpexplorer','name' => 'fa wpexplorer'],
            ['icon' => 'fa-wpforms','name' => 'fa wpforms'],
            ['icon' => 'fa-wrench','name' => 'fa wrench'],
            ['icon' => 'fa-xing','name' => 'fa xing'],
            ['icon' => 'fa-xing-square','name' => 'fa xing square'],
            ['icon' => 'fa-y-combinator','name' => 'fa y combinator'],
            ['icon' => 'fa-y-combinator-square','name' => 'fa y combinator square'],
            ['icon' => 'fa-yahoo','name' => 'fa yahoo'],
            ['icon' => 'fa-yc','name' => 'fa yc'],
            ['icon' => 'fa-yc-square','name' => 'fa yc square'],
            ['icon' => 'fa-yelp','name' => 'fa yelp'],
            ['icon' => 'fa-yen','name' => 'fa yen'],
            ['icon' => 'fa-yoast','name' => 'fa yoast'],
            ['icon' => 'fa-youtube','name' => 'fa youtube'],
            ['icon' => 'fa-youtube-play','name' => 'fa youtube play'],
            ['icon' => 'fa-youtube-square','name' => 'fa youtube square']
        ]);
    }
}
